# -*- coding: utf-8 -*-
"""mnist-pytorch-classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrVb3Z2nV5FBh-TuLkUzDsslMLqz83eT

**Import Libraries**
"""

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

"""**Dataset and DataLoader**"""

transform = transforms.ToTensor()

train_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)

"""**Build the Model**"""

model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28 * 28, 128),
    nn.ReLU(),
    nn.Linear(128, 10)
)
print(model)

"""**Define Loss and Optimizer**"""

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

"""**Complete Training Loop**"""

epochs = 5

for epoch in range(epochs):

    for images, labels in train_loader:

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

"""**Save the Model**"""

torch.save(model.state_dict(), "saved_model.pth")