# -*- coding: utf-8 -*-
"""PyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEXQpha45AwSjme5IEhnlVgsny6INJrO
"""

pip install torch

"""**Tensors**

"""

import torch
scalar=torch.tensor(8)
vector=torch.tensor([1,2,3])
matrix=torch.tensor([[12,23],[46,56]])
print(scalar)
print(vector)
print(matrix)

"""Tensor **Operations**"""

import torch

a = torch.tensor([2, 4, 6])
b = torch.tensor([1, 3, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

"""**Matrix** **Multiplication**"""

import torch

A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(A, B))

"""**Reshaping**

"""

import torch

x = torch.arange(12)

print(x.reshape(3, 4))
print(x.reshape(2, 6))
print(x.reshape(4, 3))

"""**Autograd (Gradient)**"""

import torch
x=torch.tensor(3.2,requires_grad=True)
y=x**2
y.backward()
print('gradient:',x.grad)

"""**Simple Neural Network**"""

import torch
import torch.nn as nn
model=nn.Sequential(
    nn.Linear(10,20),
    nn.ReLU(),
    nn.Linear(20,1) # Changed from 4 to 20 to match the output of the previous layer
)

print(model)

"""**Forward Pass**"""

import torch

x = torch.randn(5, 10)


output = model(x)

print(output)

"""**Loss Function**"""

import torch
import torch.nn as nn

loss_fn = nn.MSELoss()

pred = torch.tensor([2.0])
actual = torch.tensor([3.0])

loss = loss_fn(pred, actual)

print(loss)

"""**Optimizer**"""

import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.01)

print(optimizer)

"""**Training Loop**"""

for epoch in range(5):
    optimizer.zero_grad()

    output = model(x)

    target = torch.randn(5, 1)

    loss = loss_fn(output, target)

    loss.backward()

    optimizer.step()

    print(f"Epoch {epoch+1}: Loss = {loss.item()}")